### ISSUE TITLE
Need an example file of input file

### ISSUE THREAD

**Issue by YangChaoCN** [santeripuranen/SpydrPick#1]
Hi Santeri,

SpydrPick looks a great tool for epistasis detection, I like it. However, I have some problems to use it because don't know the exact input file format, could you provide an example of the input file?

Best regards
Chao

**Comment by jhuun** [comment]
Hi Chao!

Thanks for your interest! I'm the second developer of SpydrPick and I wrote the current prototype version. A much more efficient development version is almost ready: it only needs some final tweaks before we officially release it. However, you may already try that version out since the source code is available and it should be a lot more user-friendly. It accepts FASTA files (https://en.wikipedia.org/wiki/FASTA_format) directly and supports sequence reweighting. To build the development version, run the following in the base directory:
```
mkdir build
cd build
cmake ..
make SpydrPick
```
The binary `SpydrPick` will be created in the `/bin` folder inside. Use `SpydrPick -h` to view the list of available options. It outputs a text file with the top pairs (each pair being two positions, mutual information value, distance of the positions in the genome and the ARACNE flag [1=direct edge]). We will soon update the Readme.md file to reflect the new version. The development version requires the following dependencies:
* A C++14 compliant compiler (development was done using the [GNU C++ compiler](https://gcc.gnu.org/))
* [CMake](https://cmake.org/)
* [Boost](https://www.boost.org/)
* [Intel(R) Threading Building Blocks (TBB)](https://www.threadingbuildingblocks.org/)

Please use GCC 7 Series. Also make sure apegrunt (in `/externals/apegrunt`) uses the development branch.

----

If you want to use the prototype version, a FASTA formatted file must be converted into a binary file (https://en.wikipedia.org/wiki/Binary_file) as follows. 

1) Create a column-major data file.
The nucleic acid codes {-, a, c, g, t} must be encoded as {0, 1, 2, 3, 4} (respectively). Create a data matrix such that each sequence corresponds to a row and each position in the sequence corresponds to a column. Then, the data matrix must be stored in binary format (32 bit integers) in column-major order (https://en.wikipedia.org/wiki/Row-_and_column-major_order).

2) Create a weights file.
The prototype version doesn't support sequence reweighting, so you have to calculate the weights yourself (see e.g. "Sequence reweighting" in https://www.biorxiv.org/content/10.1101/523407v1). The pre-calculated weights must be stored in binary format (doubles), one for each sequence/row.

3) Create a loci file.
The code encodes the locus positions as {0, 1, ...} in read-order. The mapping to the actual locus indices must be provided in binary format (32 bit integers), one for each position/column.

Supply the data file with `-f`, the loci file with `-l` and the weights file with `-w`, then the number of positions/columns with `-d` and the number of sequences/rows with `-n`. For example:
```
./build/mi_gwes -f path_to_data -l path_to_loci -w path_to_weights -d number_of_variables -n number_of_samples -t number_of_threads -o output_file_prefix
```
Then, the ARACNE procedure must be run in another standalone program, but it can use these same input files:
```
./build/aracne -e output_file_prefix_count_edges -m output_file_prefix_count_mi -n count -t number_of_threads -o aracne_output_file
```

I apologize that the prototype version is quite confusing to use! I recommend using the development version if possible.

Best regards
Juri Kuronen

**Comment by YangChaoCN** [comment]
Thank you Juri,

Looking forward to the new version!

I tried to install the development version and failed, here's the error information. 

PS: If the new version is ready, you can ignore this error, I'll try the new version.

make SpydrPick

[ 57%] Building CXX object src/CMakeFiles/SpydrPick.dir/SpydrPick.cpp.o
In file included from /home/ubuntu/SpydrPick/externals/apegrunt/include/apegrunt/State_block.hpp:186:0,
                 from /home/ubuntu/SpydrPick/externals/apegrunt/include/apegrunt/Alignment_interface.hpp:37,
                 from /home/ubuntu/SpydrPick/externals/apegrunt/include/apegrunt/Alignment.h:26,
                 from /home/ubuntu/SpydrPick/externals/apegrunt/include/apegrunt/Apegrunt.h:27,
                 from /home/ubuntu/SpydrPick/src/SpydrPick.cpp:31:
/home/ubuntu/SpydrPick/externals/apegrunt/include/misc/SIMD_intrinsics.h:26:66: note: #pragma message: Vectorization using SIMD intrinsics is ENABLED.
 #pragma message("Vectorization using SIMD intrinsics is ENABLED.")
                                                                  ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/misc/SIMD_intrinsics.h:38:39: note: #pragma message: Using AVX intrinsics
 #pragma message("Using AVX intrinsics")
                                       ^
In file included from /home/ubuntu/SpydrPick/src/SpydrPick.cpp:38:0:
/home/ubuntu/SpydrPick/include/SpydrPick.hpp:34:45: note: #pragma message: Compiling with TBB support
 #pragma message("Compiling with TBB support")
                                             ^
In file included from /home/ubuntu/SpydrPick/include/SpydrPick.hpp:51:0,
                 from /home/ubuntu/SpydrPick/src/SpydrPick.cpp:38:
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:103:21: error: enclosing class of constexpr non-static member function 'apegrunt::Edge::my_type& apegrunt::Edge::operator=(const my_type&)' is not a literal type
  constexpr my_type& operator=( const my_type& rhs ) { m_id = rhs.m_id; m_w = rhs.m_w; }
                     ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:89:8: note: 'apegrunt::Edge' is not literal because:
 struct Edge : public apegrunt::extend_comparison_operators
        ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:89:8: note:   'apegrunt::Edge' is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:108:24: error: enclosing class of constexpr non-static member function 'apegrunt::Edge::id_t apegrunt::Edge::id() const' is not a literal type
  inline constexpr id_t id() const { return m_id; }
                        ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:109:44: error: enclosing class of constexpr non-static member function 'apegrunt::EdgeID::node_id_t apegrunt::Edge::node1() const' is not a literal type
  inline constexpr typename id_t::node_id_t node1() const { return m_id.first(); }
                                            ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:110:44: error: enclosing class of constexpr non-static member function 'apegrunt::EdgeID::node_id_t apegrunt::Edge::node2() const' is not a literal type
  inline constexpr typename id_t::node_id_t node2() const { return m_id.second(); }
                                            ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:111:26: error: enclosing class of constexpr non-static member function 'apegrunt::Edge::real_t apegrunt::Edge::weight() const' is not a literal type
  inline constexpr real_t weight() const { return m_w; }
                          ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:112:19: error: enclosing class of constexpr non-static member function 'apegrunt::Edge::operator bool() const' is not a literal type
  inline constexpr operator bool() const { return bool(m_id); }
                   ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:113:24: error: enclosing class of constexpr non-static member function 'void apegrunt::Edge::set()' is not a literal type
  inline constexpr void set() { m_id.set(); }
                        ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:114:24: error: enclosing class of constexpr non-static member function 'void apegrunt::Edge::unset()' is not a literal type
  inline constexpr void unset() { m_id.unset(); }
                        ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:116:24: error: enclosing class of constexpr non-static member function 'bool apegrunt::Edge::operator==(const my_type&) const' is not a literal type
  inline constexpr bool operator==( const my_type& rhs ) const { return m_id == rhs.m_id; }
                        ^
/home/ubuntu/SpydrPick/externals/apegrunt/include/graph/Graph.hpp:117:24: error: enclosing class of constexpr non-static member function 'bool apegrunt::Edge::operator<(const my_type&) const' is not a literal type
  inline constexpr bool operator<( const my_type& rhs ) const { return m_id < rhs.m_id; }
                        ^
src/CMakeFiles/SpydrPick.dir/build.make:62: recipe for target 'src/CMakeFiles/SpydrPick.dir/SpydrPick.cpp.o' failed
make[3]: *** [src/CMakeFiles/SpydrPick.dir/SpydrPick.cpp.o] Error 1
CMakeFiles/Makefile2:215: recipe for target 'src/CMakeFiles/SpydrPick.dir/all' failed
make[2]: *** [src/CMakeFiles/SpydrPick.dir/all] Error 2
CMakeFiles/Makefile2:227: recipe for target 'src/CMakeFiles/SpydrPick.dir/rule' failed
make[1]: *** [src/CMakeFiles/SpydrPick.dir/rule] Error 2
Makefile:144: recipe for target 'SpydrPick' failed
make: *** [SpydrPick] Error 2

Best regards
Chao

**Comment by santeripuranen** [comment]
Hi Chao,
Thanks for your input!

This looks like a compiler-related issue. What compiler and version are you using?

Development was done using GCC 7.3.0, which should work fine, but we're about to switch to 8-series GCC, as soon as we have resolved all code issues that currently prevent us from using that line.

Best regards,
Santeri

**Comment by YangChaoCN** [comment]
Thank you, Santeri

New problems now, can't find apegrunt/Distance.hpp.

[ 70%] Building CXX object src/CMakeFiles/SpydrPick.dir/SpydrPick.cpp.o
In file included from /home/ubuntu/SpydrPick/include/SpydrPick.hpp:54:0,
                 from /home/ubuntu/SpydrPick/src/SpydrPick.cpp:38:
/home/ubuntu/SpydrPick/include/mi.hpp:34:33: fatal error: apegrunt/Distance.hpp: No such file or directory
compilation terminated.

Best regards
Chao

**Comment by santeripuranen** [comment]
The SpydrPick repo is not in sync with the apegrunt submodule. A simple "git pull" in the SpydrPick folder will not update any submodules. Try "git submodule update --recursive --remote", that should take care of it.

-Santeri

**Comment by YangChaoCN** [comment]
Thank you for your helps, Santeri and Juri!

SpydrPick is finally working now. 
Looking forward your new version.

Chao

**Comment by santeripuranen** [comment]
You're welcome!

Just to be clear: the binary that you have now compiled _is_ the new version. But keep an eye on this repo, since there will likely be a number of small fixes and feature additions in the coming days/weeks.

-Santeri
