### ISSUE TITLE
Could you explain the gap_effect column?

### ISSUE THREAD

**Issue by jamiethompson77** [santeripuranen/SpydrPick#6]
I'm just wondering whether there is a threshold for gap_effect at which to exclude putative links.  It is my understanding that high values of gap_effect indicate that the MI value is likely to be explained by gaps.  My gap_effect values range from -11.1 to 29.9.  Would it be wise to ignore all putative links with gap_effect higher than 0?

**Comment by santeripuranen** [comment]
Hi Jamie,

Well, if you want to be super stringent then you could throw out everything with non-zero _gap\_effect_. That would be more or less equivalent to filtering out all gap-containing data columns to begin with (using `--gap-threshold=0`). I wouldn't suggest that you do that by default, though, since it's almost inevitable that any real genome alignment will contain gaps, and there could be interesting biology behind those gappy positions, too, depending on the quality of your data/alignment. Gappy positions could for example be part of strong links with a weak or negligible gap influence, or there could even be a biologically really interesting deletion or insertion in a subset of your samples that gives rise to a high _gap\_effect_ value.

The _gap\_effect_ isn't quite as robust and well-rounded a quality measure as one might hope. It's more of a quick indicator of potential problems: the higher the value, the more suspicious one should be about that particular hit. As such, I don't have a hard threshold for when one should become seriously worried. If there are many suspicious-looking high ranking hits, then what I would suggest as a first measure is to take a look at whether the gap patterns are shared among high scoring pairs. If they are, then that could be a problem, which you might try to solve by removing the samples that contribute to the observed gap patterns, prior to re-running SpydrPick. If they're not, then it might not be a huge problem. I would still prefer to try finding out what gives rise to the gaps in the first place. It could be something benign or it could be something potentially worrisome from upstream, such as sequencing errors, misalignment, etc.

Best regards,
Santeri

**Comment by jamiethompson77** [comment]
Hi Santeri,

Thanks for such a comprehensive reply.  So should I look in the alignment at links with high gap-effect and see whether the isolates with gaps are numerous and shared?  And if I find any that fit this criteria, should I re-run SpydrPick rather than just ignoring the links?

Best wishes,
Jamie

**Comment by santeripuranen** [comment]
Hi Jamie,

Whether you decide to remove the offending samples and re-run the analysis or simply choose to ignore hits with high `gap_effect` is entirely up to you.. I'd say go with the latter option if there's just a handful of them and you're in a hurry. If there's a lot of them then do it the other way. But as I alluded to previously, it's always a good idea to know your data. Although there's likely just something trivial behind those gappy positions, you'll never know for sure what it is unless you really dig into it. Who knows, you might discover something interesting in the process.

Best regards,
Santeri
